runtime: nodejs20
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
env: standard

handlers:
  - url: /(.*\.css)
    static_files: dist/frontend/\1
    upload: dist/frontend/.*\.css
    mime_type: text/css
    expiration: "10m"

  - url: /(.*\.js)
    static_files: dist/frontend/\1
    upload: dist/frontend/.*\.js
    mime_type: application/javascript
    expiration: "10m"

  - url: /(.*\.(ico|jpg|png|svg))
    static_files: dist/frontend/\1
    upload: dist/frontend/.*\.(ico|jpg|png|svg)
    mime_type: image/\2
    expiration: "10m"

  - url: /(.*\.(woff|woff2|ttf))
    static_files: dist/frontend/\1
    upload: dist/frontend/.*\.(woff|woff2|ttf)
    mime_type: font/\2
    expiration: "10m"

  - url: /.*
    static_files: dist/frontend/index.html
    upload: dist/frontend/index.html
