runtime: nodejs20 # or whichever Node.js version is appropriate
env: standard

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|ico|json|svg|woff|woff2|ttf))$
    static_files: dist/frontend/browser/\1
    upload: dist/frontend/browser/.*\.(gif|png|jpg|css|js|ico|json|svg|woff|woff2|ttf)$
    secure: always
  - url: /.*
    static_files: dist/frontend/browser/index.html
    upload: dist/frontend/browser/index.html
    secure: always
